# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eebe7ab869d4aecb70b6f694c7377cf00629771cb22ecb3b796be8e99af4261bc42a68554872b0896b5c3918786cb3be7824d4a87afc96e6b0046eb24c38d196

test:
  secret_key_base: c2e88b50c2c33033ff860803d38fbc59edf8b353759760cedd1df9496f597aef49a9bb9368e42aae9bc61f92994bcd8051d78a7b9aad4b4995a71bed7590d92b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
